<?php
require_once __DIR__.'/../../includes/session.php';
$title = 'Ambientes - '.APP_NAME;use Controllers\AuthController;use Models\Location;AuthController::requireRole('admin','coordinator');$items=Location::all();$api=appUrl('/api/locations.php');$csrf=csrfToken();require_once __DIR__.'/../partials/header.php';
?>
<div class="page-header"><div><h1 class="page-title">Ambientes</h1><p class="page-subtitle">Cadastre laboratórios, salas e espaços onde os equipamentos ficam guardados ou utilizados.</p></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#locationModal" onclick="newLocation()"><i data-lucide="map-pin-plus"></i> Novo ambiente</button></div>
<div class="card"><div class="card-body p-0 p-md-3"><div class="table-responsive"><table class="table mobile-cards"><thead><tr><th>Unidade / ambiente</th><th>Cidade</th><th>Bloco</th><th>Andar</th><th>Sala</th><th>Laboratório</th><th class="text-end">Ações</th></tr></thead><tbody><?php foreach($items as $x):?><tr><td data-label="Unidade"><strong><?=e($x['unit_name'])?></strong></td><td data-label="Cidade"><?=e($x['city'])?></td><td data-label="Bloco"><?=e($x['block_name']?:'-')?></td><td data-label="Andar"><?=e($x['floor']?:'-')?></td><td data-label="Sala"><?=e($x['room']?:'-')?></td><td data-label="Laboratório"><?=e($x['laboratory']?:'-')?></td><td data-label="Ações"><div class="table-actions"><button class="btn btn-outline-primary btn-sm" onclick="editLocation(<?=$x['id']?>)"><i data-lucide="pencil"></i></button><button class="btn btn-outline-danger btn-sm" onclick="deleteLocation(<?=$x['id']?>)"><i data-lucide="trash-2"></i></button></div></td></tr><?php endforeach;?></tbody></table></div></div></div>
<div class="modal fade" id="locationModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-scrollable"><div class="modal-content"><form id="locationForm"><div class="modal-header"><h2 class="modal-title fs-5" id="locationTitle">Novo ambiente</h2><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><?=csrfField()?><input type="hidden" name="action" id="locationAction" value="create"><input type="hidden" name="id" id="locationId"><div class="row g-3"><div class="col-md-7"><label class="form-label">Unidade / escola *</label><input class="form-control" name="unit_name" id="lUnit" required></div><div class="col-md-5"><label class="form-label">Cidade *</label><input class="form-control" name="city" id="lCity" required></div><div class="col-md-8"><label class="form-label">Rua</label><input class="form-control" name="street" id="lStreet"></div><div class="col-md-4"><label class="form-label">Número</label><input class="form-control" name="number" id="lNumber"></div><div class="col-md-4"><label class="form-label">Bloco</label><input class="form-control" name="block_name" id="lBlock"></div><div class="col-md-4"><label class="form-label">Andar</label><input class="form-control" name="floor" id="lFloor"></div><div class="col-md-4"><label class="form-label">Sala</label><input class="form-control" name="room" id="lRoom"></div><div class="col-md-6"><label class="form-label">Laboratório / espaço</label><input class="form-control" name="laboratory" id="lLab" placeholder="Ex.: Laboratório de Informática"></div><div class="col-12"><label class="form-label">Observações</label><textarea class="form-control" rows="3" name="observations" id="lNotes"></textarea></div></div></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancelar</button><button class="btn btn-primary">Salvar</button></div></form></div></div></div>
<script>
const locationApi=<?=json_encode($api)?>,locationCsrf=<?=json_encode($csrf)?>;function newLocation(){locationForm.reset();locationAction.value='create';locationId.value='';locationTitle.textContent='Novo ambiente'}async function editLocation(id){try{const r=await fetch(locationApi+'?action=show&id='+id),d=await r.json();if(!d.success)throw new Error(d.message);const x=d.data;locationAction.value='update';locationId.value=x.id;lUnit.value=x.unit_name;lCity.value=x.city;lStreet.value=x.street||'';lNumber.value=x.number||'';lBlock.value=x.block_name||'';lFloor.value=x.floor||'';lRoom.value=x.room||'';lLab.value=x.laboratory||'';lNotes.value=x.observations||'';locationTitle.textContent='Editar ambiente';new bootstrap.Modal(document.getElementById('locationModal')).show()}catch(e){notifyError(e)}}async function deleteLocation(id){if(!confirm('Excluir este ambiente? Os equipamentos continuarão cadastrados, mas ficarão sem localização.'))return;try{await apiPost(locationApi,{action:'delete',id,_csrf:locationCsrf});location.reload()}catch(e){notifyError(e)}}locationForm.addEventListener('submit',async e=>{e.preventDefault();try{await apiPost(locationApi,new FormData(e.target));location.reload()}catch(err){notifyError(err)}})
</script><?php require_once __DIR__.'/../partials/footer.php';?>
