<?php
require_once __DIR__.'/../../includes/session.php';
$title = 'Equipamentos - '.APP_NAME;
use Controllers\AuthController;use Models\Equipment;use Models\Category;use Models\Location;
AuthController::requireAuth();$items=Equipment::all();$cats=Category::all();$locs=Location::all();$api=appUrl('/api/equipment.php');$csrf=csrfToken();$canManage=can('manage_equipment');$canSchedule=can('schedule_equipment');require_once __DIR__.'/../partials/header.php';
?>
<div class="page-header"><div><h1 class="page-title">Equipamentos</h1><p class="page-subtitle">Consulte o patrimônio tecnológico e agende os itens disponíveis para suas aulas.</p></div><?php if($canManage):?><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#equipmentModal" onclick="newEquipment()"><i data-lucide="plus"></i> Novo equipamento</button><?php endif;?></div>
<div class="card"><div class="card-header"><div class="toolbar"><div class="search-box"><i data-lucide="search"></i><input class="form-control" placeholder="Buscar equipamento ou patrimônio" data-search-table="#equipmentTable"></div><span class="ms-auto small muted"><?=count($items)?> registros</span></div></div><div class="card-body p-0 p-md-3"><div class="table-responsive"><table class="table mobile-cards" id="equipmentTable"><thead><tr><th>Equipamento</th><th>Patrimônio</th><th>Categoria</th><th>Ambiente</th><th>Status</th><?php if($canManage||$canSchedule):?><th class="text-end">Ações</th><?php endif;?></tr></thead><tbody><?php foreach($items as $i):?><tr><td data-label="Equipamento"><strong><?=e($i['name'])?></strong></td><td data-label="Patrimônio"><?=e($i['patrimony_code'])?></td><td data-label="Categoria"><?=e($i['category_name']?:'-')?></td><td data-label="Ambiente"><?=e($i['location_name']?:'-')?></td><td data-label="Status"><?=getStatusBadge($i['status'])?></td><?php if($canManage||$canSchedule):?><td data-label="Ações"><div class="table-actions"><?php if($canSchedule && !in_array($i['status'],['maintenance','inactive'],true)):?><a class="btn btn-primary btn-sm" href="<?=e(appUrl('/views/loans/index.php?new=1&equipment_id='.(int)$i['id']))?>"><i data-lucide="calendar-plus"></i> Agendar</a><?php endif;?><?php if($canManage):?><button class="btn btn-outline-primary btn-sm" onclick="editEquipment(<?=$i['id']?>)"><i data-lucide="pencil"></i> Editar</button><?php if($i['status']!=='inactive'):?><button class="btn btn-outline-danger btn-sm" onclick="archiveEquipment(<?=$i['id']?>)"><i data-lucide="archive"></i></button><?php endif;?><?php endif;?></div></td><?php endif;?></tr><?php endforeach;?></tbody></table></div><?php if(!$items):?><div class="empty-state"><i data-lucide="monitor"></i><div>Nenhum equipamento cadastrado.</div></div><?php endif;?></div></div>
<?php if($canManage):?><div class="modal fade" id="equipmentModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-scrollable"><div class="modal-content"><form id="equipmentForm"><div class="modal-header"><div><h2 class="modal-title fs-5" id="equipmentModalTitle">Novo equipamento</h2><div class="help-text">Identifique o item de forma que qualquer servidor consiga localizá-lo.</div></div><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><?=csrfField()?><input type="hidden" name="action" id="equipmentAction" value="create"><input type="hidden" name="id" id="equipmentId"><div class="row g-3"><div class="col-md-7"><label class="form-label">Nome *</label><input class="form-control" name="name" id="eName" required></div><div class="col-md-5"><label class="form-label">Código patrimonial *</label><input class="form-control" name="patrimony_code" id="eCode" required></div><div class="col-md-6"><label class="form-label">Categoria</label><select class="form-select" name="category_id" id="eCategory"><option value="">Sem categoria</option><?php foreach($cats as $c):?><option value="<?=$c['id']?>"><?=e($c['name'])?></option><?php endforeach;?></select></div><div class="col-md-6"><label class="form-label">Ambiente</label><select class="form-select" name="location_id" id="eLocation"><option value="">Sem ambiente</option><?php foreach($locs as $l):?><option value="<?=$l['id']?>"><?=e($l['display_name'])?></option><?php endforeach;?></select></div><div class="col-md-4"><label class="form-label">Status</label><select class="form-select" name="status" id="eStatus"><option value="available">Disponível</option><option value="maintenance">Em manutenção</option><option value="inactive">Inativo</option><option value="reserved">Reservado</option><option value="borrowed">Emprestado</option></select></div><div class="col-md-4"><label class="form-label">Aquisição</label><input class="form-control" type="date" name="acquisition_date" id="eAcquisition"></div><div class="col-md-4"><label class="form-label">Garantia até</label><input class="form-control" type="date" name="warranty_until" id="eWarranty"></div><div class="col-md-4"><label class="form-label">Valor de compra</label><input class="form-control" type="number" min="0" step="0.01" name="purchase_value" id="eValue"></div><div class="col-12"><label class="form-label">Descrição / observações</label><textarea class="form-control" rows="3" name="description" id="eDescription"></textarea></div></div></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancelar</button><button class="btn btn-primary">Salvar</button></div></form></div></div></div>
<script>
const equipmentApi=<?=json_encode($api)?>,equipmentCsrf=<?=json_encode($csrf)?>;
function newEquipment(){equipmentForm.reset();equipmentAction.value='create';equipmentId.value='';equipmentModalTitle.textContent='Novo equipamento';eStatus.value='available'}
async function editEquipment(id){try{const r=await fetch(equipmentApi+'?action=show&id='+id),d=await r.json();if(!d.success)throw new Error(d.message);const x=d.data;equipmentAction.value='update';equipmentId.value=x.id;eName.value=x.name;eCode.value=x.patrimony_code;eCategory.value=x.category_id||'';eLocation.value=x.location_id||'';eStatus.value=x.status;eAcquisition.value=x.acquisition_date||'';eWarranty.value=x.warranty_until||'';eValue.value=x.purchase_value||'';eDescription.value=x.description||'';equipmentModalTitle.textContent='Editar equipamento';new bootstrap.Modal(document.getElementById('equipmentModal')).show()}catch(e){notifyError(e)}}
async function archiveEquipment(id){if(!confirm('Arquivar este equipamento? O histórico será mantido.'))return;try{await apiPost(equipmentApi,{action:'delete',id,_csrf:equipmentCsrf});location.reload()}catch(e){notifyError(e)}}
equipmentForm.addEventListener('submit',async e=>{e.preventDefault();try{await apiPost(equipmentApi,new FormData(e.target));location.reload()}catch(err){notifyError(err)}})
</script><?php endif;?>
<?php require_once __DIR__.'/../partials/footer.php';?>
