<?php
require_once __DIR__ . '/../../includes/session.php';
$title = 'Alunos - '.APP_NAME;
use Controllers\AuthController;use Models\Student;
AuthController::requireRole('admin','coordinator');$students=Student::all();$api=appUrl('/api/students.php');$csrf=csrfToken();
require_once __DIR__ . '/../partials/header.php';
?>
<div class="page-header"><div><h1 class="page-title">Alunos</h1><p class="page-subtitle">Cadastro escolar usado para identificar responsáveis pelos empréstimos, sem criar login para o estudante.</p></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#studentModal" onclick="newStudent()"><i data-lucide="user-plus"></i> Novo aluno</button></div>
<div class="card"><div class="card-header"><div class="toolbar"><div class="search-box"><i data-lucide="search"></i><input class="form-control" placeholder="Buscar por nome, matrícula ou turma" data-search-table="#studentsTable"></div><span class="ms-auto small muted"><?=count($students)?> registros</span></div></div><div class="card-body p-0 p-md-3"><div class="table-responsive"><table class="table mobile-cards" id="studentsTable"><thead><tr><th>Aluno</th><th>Matrícula</th><th>Ano/Série</th><th>Turma</th><th>Responsável</th><th>Status</th><th class="text-end">Ações</th></tr></thead><tbody><?php foreach($students as $s):?><tr><td data-label="Aluno"><strong><?=e($s['name'])?></strong></td><td data-label="Matrícula"><?=e($s['registration'])?></td><td data-label="Ano/Série"><?=e($s['grade'])?></td><td data-label="Turma"><?=e($s['class_name'])?></td><td data-label="Responsável"><?=e($s['guardian_name']?:'-')?><small class="d-block muted"><?=e($s['guardian_phone']?:'')?></small></td><td data-label="Status"><?=getStatusBadge($s['status'])?></td><td data-label="Ações"><div class="table-actions"><button class="btn btn-outline-primary btn-sm" onclick="editStudent(<?=$s['id']?>)"><i data-lucide="pencil"></i> Editar</button><?php if($s['status']==='active'):?><button class="btn btn-outline-danger btn-sm" onclick="archiveStudent(<?=$s['id']?>)"><i data-lucide="archive"></i></button><?php endif;?></div></td></tr><?php endforeach;?></tbody></table></div><?php if(!$students):?><div class="empty-state"><i data-lucide="users"></i><div>Nenhum aluno cadastrado.</div></div><?php endif;?></div></div>
<div class="modal fade" id="studentModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-scrollable"><div class="modal-content"><form id="studentForm"><div class="modal-header"><div><h2 class="modal-title fs-5" id="studentModalTitle">Novo aluno</h2><div class="help-text">Dados essenciais para identificar o estudante e sua turma.</div></div><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><?=csrfField()?><input type="hidden" name="action" id="studentAction" value="create"><input type="hidden" name="id" id="studentId"><div class="row g-3"><div class="col-md-7"><label class="form-label">Nome completo *</label><input class="form-control" name="name" id="sName" required></div><div class="col-md-5"><label class="form-label">Matrícula *</label><input class="form-control" name="registration" id="sRegistration" required></div><div class="col-md-4"><label class="form-label">Ano/Série *</label><input class="form-control" name="grade" id="sGrade" placeholder="Ex.: 6º ano" required></div><div class="col-md-4"><label class="form-label">Turma *</label><input class="form-control" name="class_name" id="sClass" placeholder="Ex.: A" required></div><div class="col-md-4"><label class="form-label">Nascimento</label><input class="form-control" type="date" name="birth_date" id="sBirth"></div><div class="col-md-7"><label class="form-label">Responsável familiar</label><input class="form-control" name="guardian_name" id="sGuardian"></div><div class="col-md-5"><label class="form-label">Telefone do responsável</label><input class="form-control" name="guardian_phone" id="sPhone" inputmode="tel"></div><div class="col-md-4"><label class="form-label">Status</label><select class="form-select" name="status" id="sStatus"><option value="active">Ativo</option><option value="inactive">Inativo</option></select></div><div class="col-12"><label class="form-label">Observações</label><textarea class="form-control" rows="3" name="notes" id="sNotes" placeholder="Informações administrativas relevantes. Evite dados sensíveis desnecessários."></textarea></div></div></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancelar</button><button class="btn btn-primary" type="submit">Salvar aluno</button></div></form></div></div></div>
<script>
const studentApi=<?=json_encode($api)?>,csrf=<?=json_encode($csrf)?>;
function newStudent(){const f=document.getElementById('studentForm');f.reset();studentAction.value='create';studentId.value='';studentModalTitle.textContent='Novo aluno';sStatus.value='active';}
async function editStudent(id){try{const r=await fetch(studentApi+'?action=show&id='+id);const d=await r.json();if(!d.success)throw new Error(d.message);const s=d.data;studentAction.value='update';studentId.value=s.id;sName.value=s.name;sRegistration.value=s.registration;sGrade.value=s.grade;sClass.value=s.class_name;sBirth.value=s.birth_date||'';sGuardian.value=s.guardian_name||'';sPhone.value=s.guardian_phone||'';sStatus.value=s.status;sNotes.value=s.notes||'';studentModalTitle.textContent='Editar aluno';new bootstrap.Modal(document.getElementById('studentModal')).show();}catch(e){notifyError(e)}}
async function archiveStudent(id){if(!confirm('Arquivar este aluno? O histórico de empréstimos será preservado.'))return;try{await apiPost(studentApi,{action:'delete',id,_csrf:csrf});location.reload()}catch(e){notifyError(e)}}
document.getElementById('studentForm').addEventListener('submit',async e=>{e.preventDefault();try{await apiPost(studentApi,new FormData(e.target));location.reload()}catch(err){notifyError(err)}});
</script>
<?php require_once __DIR__ . '/../partials/footer.php'; ?>
