<?php
require_once __DIR__.'/../../includes/session.php';
$title = 'Professores e acessos - '.APP_NAME;use Controllers\AuthController;use Models\User;AuthController::requireRole('admin');$users=User::all();$api=appUrl('/api/users.php');$csrf=csrfToken();require_once __DIR__.'/../partials/header.php';
?>
<div class="page-header"><div><h1 class="page-title">Professores e acessos</h1><p class="page-subtitle">Crie uma conta para cada professor ou profissional autorizado. Professores com perfil ativo podem entrar no sistema e fazer seus próprios agendamentos.</p></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#userModal" onclick="newUser()"><i data-lucide="user-plus"></i> Novo acesso</button></div>
<div class="card"><div class="card-header"><div class="search-box"><i data-lucide="search"></i><input class="form-control" placeholder="Buscar nome ou e-mail" data-search-table="#usersTable"></div></div><div class="card-body p-0 p-md-3"><div class="table-responsive"><table class="table mobile-cards" id="usersTable"><thead><tr><th>Profissional</th><th>E-mail</th><th>Perfil</th><th>Status</th><th>Cadastro</th><th class="text-end">Ações</th></tr></thead><tbody><?php foreach($users as $u):?><tr><td data-label="Profissional"><strong><?=e($u['name'])?></strong></td><td data-label="E-mail"><?=e($u['email'])?></td><td data-label="Perfil"><?=getStatusBadge($u['role'])?></td><td data-label="Status"><?=getStatusBadge($u['status'])?></td><td data-label="Cadastro"><?=e(formatDate($u['created_at']))?></td><td data-label="Ações"><div class="table-actions"><button class="btn btn-outline-primary btn-sm" onclick="editUser(<?=$u['id']?>)"><i data-lucide="pencil"></i> Editar</button><?php if($u['status']==='active'&&$u['id']!=$_SESSION['user_id']):?><button class="btn btn-outline-danger btn-sm" onclick="archiveUser(<?=$u['id']?>)"><i data-lucide="user-x"></i></button><?php endif;?></div></td></tr><?php endforeach;?></tbody></table></div></div></div>
<div class="modal fade" id="userModal" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form id="userForm"><div class="modal-header"><div><h2 class="modal-title fs-5" id="userTitle">Novo acesso</h2><div class="help-text">Use uma conta por profissional para manter a auditoria confiável.</div></div><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><?=csrfField()?><input type="hidden" name="action" id="userAction" value="create"><input type="hidden" name="id" id="userId"><div class="mb-3"><label class="form-label">Nome *</label><input class="form-control" name="name" id="uName" required></div><div class="mb-3"><label class="form-label">E-mail *</label><input class="form-control" type="email" name="email" id="uEmail" required></div><div class="mb-3"><label class="form-label">Senha <span id="passwordRequired">*</span></label><input class="form-control" type="password" name="password" id="uPassword" minlength="8"><div class="help-text">Na edição, deixe em branco para manter a senha atual.</div></div><div class="row g-3"><div class="col-sm-7"><label class="form-label">Perfil</label><select class="form-select" name="role" id="uRole"><option value="teacher">Professor</option><option value="technician">Técnico</option><option value="coordinator">Coordenação</option><option value="admin">Administrador</option><option value="common">Usuário limitado</option></select></div><div class="col-sm-5"><label class="form-label">Status</label><select class="form-select" name="status" id="uStatus"><option value="active">Ativo</option><option value="inactive">Inativo</option></select></div></div></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancelar</button><button class="btn btn-primary">Salvar</button></div></form></div></div></div>
<script>
const userApi=<?=json_encode($api)?>,userCsrf=<?=json_encode($csrf)?>;function newUser(){userForm.reset();userAction.value='create';userId.value='';userTitle.textContent='Novo acesso';uPassword.required=true;passwordRequired.hidden=false;uRole.value='teacher';uStatus.value='active'}async function editUser(id){try{const r=await fetch(userApi+'?action=show&id='+id),d=await r.json();if(!d.success)throw new Error(d.message);const u=d.data;userAction.value='update';userId.value=u.id;uName.value=u.name;uEmail.value=u.email;uPassword.value='';uPassword.required=false;passwordRequired.hidden=true;uRole.value=u.role;uStatus.value=u.status;userTitle.textContent='Editar acesso';new bootstrap.Modal(document.getElementById('userModal')).show()}catch(e){notifyError(e)}}async function archiveUser(id){if(!confirm('Desativar este acesso? O histórico será preservado.'))return;try{await apiPost(userApi,{action:'delete',id,_csrf:userCsrf});location.reload()}catch(e){notifyError(e)}}userForm.addEventListener('submit',async e=>{e.preventDefault();try{await apiPost(userApi,new FormData(e.target));location.reload()}catch(err){notifyError(err)}})
</script><?php require_once __DIR__.'/../partials/footer.php';?>
